In [20]:

import pickle
import os

from matplotlib import pyplot as plt
from matplotlib import cm
import matplotlib.patches as mpatches

# noinspection PyUnresolvedReferences
import csv
import numpy as np
import pandas as pd

In [21]:
# read in paths
path1 = '/Users/miagrahn/wcEcoli/out/CLMLNE_test1/kb_plot_out/protein_half_lives_updated.tsv'

path2 = '/Users/miagrahn/wcEcoli/out/CLMLNE_test2/kb_plot_out/protein_half_lives_updated.tsv'

In [22]:

# read the tsvs in: 
df1 = pd.read_csv(path1, sep='\t')
df2 = pd.read_csv(path2, sep='\t')
df2.head()

,common_name,half_life(min),degradation_rate(1/s),monomer_id,degradation_rate_source,protease_assignment,ClpP_contribution,Lon_contribution,HslV_contribution,Unexplained_contribution,cistron_id,length,aa_counts,mw
0,plsC,600.0,0.000019,1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER,N_end_rule,not applicable,0.0,0.0,0.0,0.0,EG11377_RNA,245 [amino_acid],[19 15 14 6 5 11 6 17 8 22 21 14 6 12 13 ...,27465.210999999996 [g/mol]
1,fruK,600.0,0.000019,1-PFK-MONOMER,N_end_rule,not applicable,0.0,0.0,0.0,0.0,EG10337_RNA,312 [amino_acid],[30 18 11 17 4 19 11 29 4 15 30 12 8 13 13 ...,33749.587 [g/mol]
2,panE,600.0,0.000019,2-DEHYDROPANTOATE-REDUCT-MONOMER,N_end_rule,not applicable,0.0,0.0,0.0,0.0,G6239_RNA,303 [amino_acid],[25 18 16 15 6 20 15 19 12 24 34 7 7 4 14 ...,33860.64 [g/mol]
3,leuA,171.5,0.000067,2-ISOPROPYLMALATESYN-MONOMER,Nagar_et_al_ML_2021,not applicable,0.0,0.0,0.0,0.0,EG11226_RNA,523 [amino_acid],[61 27 30 29 6 41 22 35 15 39 36 27 13 15 12 ...,57281.702 [g/mol]
4,ubiE,158.0,0.000073,2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER,Nagar_et_al_ML_2021,not applicable,0.0,0.0,0.0,0.0,EG11473_RNA,251 [amino_acid],[20 15 9 19 2 11 7 19 7 11 23 16 10 13 7 ...,28074.177 [g/mol]

In [23]:
df1

,common_name,half_life(min),degradation_rate(1/s),monomer_id,degradation_rate_source,protease_assignment,ClpP_contribution,Lon_contribution,HslV_contribution,Unexplained_contribution,cistron_id,length,aa_counts,mw
0,plsC,600.0,0.000019,1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG11377_RNA,245 [amino_acid],[19 15 14 6 5 11 6 17 8 22 21 14 6 12 13 ...,27465.210999999996 [g/mol]
1,fruK,600.0,0.000019,1-PFK-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG10337_RNA,312 [amino_acid],[30 18 11 17 4 19 11 29 4 15 30 12 8 13 13 ...,33749.587 [g/mol]
2,panE,600.0,0.000019,2-DEHYDROPANTOATE-REDUCT-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,G6239_RNA,303 [amino_acid],[25 18 16 15 6 20 15 19 12 24 34 7 7 4 14 ...,33860.64 [g/mol]
3,leuA,171.5,0.000067,2-ISOPROPYLMALATESYN-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,EG11226_RNA,523 [amino_acid],[61 27 30 29 6 41 22 35 15 39 36 27 13 15 12 ...,57281.702 [g/mol]
4,ubiE,158.0,0.000073,2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,EG11473_RNA,251 [amino_acid],[20 15 9 19 2 11 7 19 7 11 23 16 10 13 7 ...,28074.177 [g/mol]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4305,ytfR,600.0,0.000019,YTFR-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12518_RNA,500 [amino_acid],[43 39 13 24 5 37 26 40 7 40 63 21 11 18 21 ...,55258.920999999995 [g/mol]
4306,ytfT,600.0,0.000019,YTFT-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12520_RNA,341 [amino_acid],[39 14 11 10 2 3 11 35 1 34 53 7 12 13 15 ...,35666.971999999994 [g/mol]
4307,znuA,5000.0,0.000002,ZNUA-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,G7017_RNA,310 [amino_acid],[36 9 7 20 2 20 16 22 13 9 34 20 7 13 16 ...,33766.248999999996 [g/mol]
4308,znuB,600.0,0.000019,ZNUB-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12368_RNA,261 [amino_acid],[33 9 3 9 2 4 5 21 2 18 47 6 13 12 10 ...,27730.621999999996 [g/mol]
4309,znuC,600.0,0.000019,ZNUC-MONOMER,N_end_rule,ClpP only,0.791491,0.0,0.158285,0.050224,G7018_RNA,251 [amino_acid],[ 9 21 10 13 4 11 11 22 12 10 42 10 5 4 13 ...,27874.475000000002 [g/mol]

In [24]:
df2

,common_name,half_life(min),degradation_rate(1/s),monomer_id,degradation_rate_source,protease_assignment,ClpP_contribution,Lon_contribution,HslV_contribution,Unexplained_contribution,cistron_id,length,aa_counts,mw
0,plsC,600.0,0.000019,1-ACYLGLYCEROL-3-P-ACYLTRANSFER-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG11377_RNA,245 [amino_acid],[19 15 14 6 5 11 6 17 8 22 21 14 6 12 13 ...,27465.210999999996 [g/mol]
1,fruK,600.0,0.000019,1-PFK-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG10337_RNA,312 [amino_acid],[30 18 11 17 4 19 11 29 4 15 30 12 8 13 13 ...,33749.587 [g/mol]
2,panE,600.0,0.000019,2-DEHYDROPANTOATE-REDUCT-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,G6239_RNA,303 [amino_acid],[25 18 16 15 6 20 15 19 12 24 34 7 7 4 14 ...,33860.64 [g/mol]
3,leuA,171.5,0.000067,2-ISOPROPYLMALATESYN-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,EG11226_RNA,523 [amino_acid],[61 27 30 29 6 41 22 35 15 39 36 27 13 15 12 ...,57281.702 [g/mol]
4,ubiE,158.0,0.000073,2-OCTAPRENYL-METHOXY-BENZOQ-METH-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,EG11473_RNA,251 [amino_acid],[20 15 9 19 2 11 7 19 7 11 23 16 10 13 7 ...,28074.177 [g/mol]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4305,ytfR,600.0,0.000019,YTFR-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12518_RNA,500 [amino_acid],[43 39 13 24 5 37 26 40 7 40 63 21 11 18 21 ...,55258.920999999995 [g/mol]
4306,ytfT,600.0,0.000019,YTFT-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12520_RNA,341 [amino_acid],[39 14 11 10 2 3 11 35 1 34 53 7 12 13 15 ...,35666.971999999994 [g/mol]
4307,znuA,5000.0,0.000002,ZNUA-MONOMER,Nagar_et_al_ML_2021,not applicable,0.000000,0.0,0.000000,0.000000,G7017_RNA,310 [amino_acid],[36 9 7 20 2 20 16 22 13 9 34 20 7 13 16 ...,33766.248999999996 [g/mol]
4308,znuB,600.0,0.000019,ZNUB-MONOMER,N_end_rule,not applicable,0.000000,0.0,0.000000,0.000000,EG12368_RNA,261 [amino_acid],[33 9 3 9 2 4 5 21 2 18 47 6 13 12 10 ...,27730.621999999996 [g/mol]
4309,znuC,600.0,0.000019,ZNUC-MONOMER,N_end_rule,ClpP only,0.791491,0.0,0.158285,0.050224,G7018_RNA,251 [amino_acid],[ 9 21 10 13 4 11 11 22 12 10 42 10 5 4 13 ...,27874.475000000002 [g/mol]

In [25]:
# tell me the differences between the two:
# get the set of all proteins in both dataframes:
proteins1 = set(df1['monomer_id'])
proteins2 = set(df2['monomer_id'])

# get the set of proteins that are in df1 but not in df2:
proteins_only_in_df1 = proteins1 - proteins2
print(f'Proteins only in df1: {proteins_only_in_df1}')

Proteins only in df1: set()

In [26]:
# get the set of proteins that are in df2 but not in df1:
proteins_only_in_df2 = proteins2 - proteins1
print(f'Proteins only in df2: {proteins_only_in_df2}')

Proteins only in df2: set()

In [27]:
col_names = set(df1.columns) | set(df2.columns)
print(f'Columns in df1: {set(df1.columns)} ({len(set(df1.columns))} columns)')
print(f'Columns in df2: {set(df2.columns)} ({len(set(df2.columns))} columns)')
print(f'All columns: {col_names} ({len(col_names)} columns)')

Columns in df1: {'HslV_contribution', 'degradation_rate(1/s)', 'degradation_rate_source', 'Lon_contribution', 'common_name', 'half_life(min)', 'cistron_id', 'aa_counts', 'Unexplained_contribution', 'monomer_id', 'ClpP_contribution', 'mw', 'protease_assignment', 'length'} (14 columns)
Columns in df2: {'HslV_contribution', 'degradation_rate(1/s)', 'degradation_rate_source', 'Lon_contribution', 'common_name', 'half_life(min)', 'cistron_id', 'aa_counts', 'Unexplained_contribution', 'monomer_id', 'ClpP_contribution', 'mw', 'protease_assignment', 'length'} (14 columns)
All columns: {'degradation_rate_source', 'Lon_contribution', 'common_name', 'cistron_id', 'aa_counts', 'protease_assignment', 'HslV_contribution', 'degradation_rate(1/s)', 'half_life(min)', 'monomer_id', 'ClpP_contribution', 'mw', 'Unexplained_contribution', 'length'} (14 columns)

In [28]:
def check_column_differences(df1, df2):
    col_names = set(df1.columns) | set(df2.columns)
    print(f'Columns in df1: {set(df1.columns)} ({len(set(df1.columns))} columns)')
    print(f'Columns in df2: {set(df2.columns)} ({len(set(df2.columns))} columns)')
    print(f'All columns: {col_names} ({len(col_names)} columns)')
    protein_ids = set(df1['monomer_id']) | set(df2['monomer_id'])
    for col in col_names:
        # check if the contents of the column are the same in both dataframes:
        if col in df1.columns and col in df2.columns:
            for monomer in protein_ids:
                val1 = df1[df1['monomer_id'] == monomer][col].values
                val2 = df2[df2['monomer_id'] == monomer][col].values
                if not np.array_equal(val1, val2):
                    print(f'Column "{col}" has different values for monomer "{monomer}" in df1 and df2.')
                    print(f'Value in df1: {val1}')
                    print(f'Value in df2: {val2}')

In [29]:
check_column_differences(df1, df2)

Columns in df1: {'HslV_contribution', 'degradation_rate(1/s)', 'degradation_rate_source', 'Lon_contribution', 'common_name', 'half_life(min)', 'cistron_id', 'aa_counts', 'Unexplained_contribution', 'monomer_id', 'ClpP_contribution', 'mw', 'protease_assignment', 'length'} (14 columns)
Columns in df2: {'HslV_contribution', 'degradation_rate(1/s)', 'degradation_rate_source', 'Lon_contribution', 'common_name', 'half_life(min)', 'cistron_id', 'aa_counts', 'Unexplained_contribution', 'monomer_id', 'ClpP_contribution', 'mw', 'protease_assignment', 'length'} (14 columns)
All columns: {'degradation_rate_source', 'Lon_contribution', 'common_name', 'cistron_id', 'aa_counts', 'protease_assignment', 'HslV_contribution', 'degradation_rate(1/s)', 'half_life(min)', 'monomer_id', 'ClpP_contribution', 'mw', 'Unexplained_contribution', 'length'} (14 columns)